apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: v6-vbb-transport-rest
  namespace: app-releases
spec:
  chart:
    spec:
      chart: simple-app
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: flux-system
      version: '^2.0.0'
  interval: 5m
  values:
    image:
      repositoryWithRegistry: "ghcr.io/derhuerst/vbb-rest" # {"$imagepolicy": "flux-system:v6-vbb-transport-rest-image-policy:name"}
      tag: 'v6_e84abb3_2023-11-07T18.26.54Z' # {"$imagepolicy": "flux-system:v6-vbb-transport-rest-image-policy:tag"}
      tagUpdatePattern: '^v6_[a-fA-F0-9]{7}_(?P<datetime>.*)Z$'
      tagUpdateExtract: '$datetime'
    exposedPort: 3000
    environment:
      HOSTNAME: 'b.v6.vbb.transport.rest'
      PORT: 3000
      REDIS_URL: 'redis://:some-password-123@redis.redis.svc.cluster.local:6379/4'
      NODE_ENV: 'production'
    hosts:
    - 'b.v6.vbb.transport.rest'
    resources:
      limits:
        cpu: 1
        memory: 600Mi
      requests:
        cpu: .3
        memory: 220Mi
    livenessProbe: '/health'
    startupProbe: '/health'
