apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: '^6.9.3'
  valuesFrom:
    - kind: Secret
      name: promtail-secret
      valuesKey: host
      targetPath: config.clients[0].url
    - kind: Secret
      name: promtail-secret
      valuesKey: username
      targetPath: config.clients[0].basic_auth.username
    - kind: Secret
      name: promtail-secret
      valuesKey: password
      targetPath: config.clients[0].basic_auth.password
  interval: 5m
