apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: db-rest
  namespace: app-releases
spec:
  chart:
    spec:
      chart: ./kubernetes/.charts/simple-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  values:
    image:
      updateTagAutomatically: false
      repositoryWithRegistry: "ghcr.io/derhuerst/db-rest"
      tag: "v5_72caa58_2023-09-19T08.59.46Z"
    exposedPort: 3000
    environment:
      PORT: 3000
    hosts:
      - "v5.db.api.bahn.guru"
    replicas: 3
    livenessProbe: false
    startupProbe: false
