apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: apps
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/secrets/apps
  prune: true
