apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-16
  namespace: postgres
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '^15.3.1'
  values:
    global:
      postgresql:
        auth:
          username: 'user'
          database: 'public-transport'
          existingSecret: 'postgres-secret'
          secretKeys:
            adminPasswordKey: 'admin-password'
            userPasswordKey: 'user-password'
            replicationPasswordKey: 'replication-password'
    primary:
      resourcesPreset: 'medium'
      persistence:
        size: '20Gi'
  interval: 5m
