apiVersion: v1
data:
    token: ENC[AES256_GCM,data:6PxoZjL3BSaiWENHauI6dkfywx2NpbdeMYRaO15SNcMmGShSHkDw7/68zqPyLgW9XkzXOzWob3c=,iv:t9h7EdUi5+yKdIZ0oSjBBzC+dM24FjgQWczirJVZ5nw=,tag:zxIbEphN6eQceqLpm34ioQ==,type:str]
kind: Secret
metadata:
    name: matrix-token
    namespace: flux-system
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T22:00:55Z"
    mac: ENC[AES256_GCM,data:TJpI7fzQtp7aD7Yk4p0X+17zw205S0rRWy3AohFxldrpWJp2OLlpuetQVem9E8pHoDwRf3bnkY10pci4xUlun4Vtnpb8B6q6bOZqMWif+pckms6eB7HzDmO6Q7Pfw/Eh5VMQ2rKY6/TZ0UBqAi8WUzY9rvmgUuly7bDBXnOKrDI=,iv:yLEQZXezw+EyUy4V9KuXJqh0wXSUMzvZ8bTJbCkNf7Q=,tag:1rrxilS9EpGSwiTT7vAwtg==,type:str]
    pgp:
        - created_at: "2026-10-03T22:00:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxER4EixexCHAQ/9GzUhn9uXWnnn68+VEMtjCwTiyIacDi9DPFHTDYTHqKTB
            U8HKNmOIWq5LjEn+ynvdjB3Y9mikREjodxW9le65F10nQqudfXlC4zhTqaOMxRsT
            YtCDnZTdpmq5DOTCaqhCMiXMzm43UmImhgwrPo+0BjqTAmQEKc7ujuYiUj30y7WK
            0CYG/7WSfkLRiIj6BpMmYIcndhAikmdSfxpVLEBSKrdst+ZUF9FZfiULL+jFmRhJ
            qoC7HXkqIa0wDgqawLTLogR5RslkSjfAVQrJvGxCknrQYiU6HuwZXX2klEWUun9q
            mErK6gDxR3pArt7kfO3U9pZjcQRQFLr8Z3J3tQL4Jjt4pDi6rXVthBp+St//rwTX
            k055daPLj3lMMWms+xUNbVpELdYIbp41Pbe+4NTw0xA6Wp608dPOyL6DR2SvSMnH
            xw3egs1hrTw2S0LXVutDzrMhZb8MBOSHF9QcJN4vu+Y5b4CUTs5JgVsoIAjxOqtA
            3mTncK5KLlqkUN8DaawmGUzYNpSNGnsKor5VszKaA+ksQsGiQ4A6aShpQbkEugK8
            Icyxlw5uQmM1ge3faMSZxQlR0it8ag5o7tfEL/QR3/br4g98RjvRP87E9Frxe8Wd
            tziO6FXT+Gn62yruS6XBHaUtBFsM7iaIXxH5e+jP0iVSoKjDpT+YCqC1XtreeNbS
            XgEDqmp1gUJFf+AhXGLe81+z1rkG4lv69LRHJJDOPNy3eWOJWRpCN/ZajDGDI1SM
            kOXw2XQszaObaFo2Ez+J2IWzVAL86KCIrv1DGVED1x/m+hfxxrbUF5DioTZy83E=
            =6kdJ
            -----END PGP MESSAGE-----
          fp: 269A9ADE0A611CD74CB8BC4434C257FCF9AB9265
    version: 3.13.3
