apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: umami
  namespace: app-releases
spec:
  chart:
    spec:
      chart: simple-app
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: flux-system
      version: '^3.0.0'
  interval: 5m
  values:
    hasSecrets: true
    image:
      updateTagAutomatically: false
      repositoryWithRegistry: "ghcr.io/umami-software/umami"
      tag: "postgresql-v2.6.2"
    exposedPort: 3000
    environment: {}
    hosts:
      - 'developer.public-transport.earth'
      - 'developer.bahn.guru'
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    livenessProbe: false
    startupProbe: false
