apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: fluent-bit
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/redis
  prune: true
  validation: client
