apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: european-transport-feeds-website
  namespace: app-releases
spec:
  chart:
    spec:
      chart: simple-app
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: flux-system
      version: '^3.0.0'
  interval: 5m
  values:
    image:
      repositoryWithRegistry: "ghcr.io/public-transport/european-transport-feeds-website" # {"$imagepolicy": "flux-system:european-transport-feeds-website-image-policy:name"}
      tag: "v1_7bf63bb_2023-09-18T02.48.42Z" # {"$imagepolicy": "flux-system:european-transport-feeds-website-image-policy:tag"}
    exposedPort: 3000
    environment:
      PORT: 3000
    hosts:
    - 'eu.data.public-transport.earth'
    # resources:
    #   limits:
    #     cpu: 200m
    #     memory: 256Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe: false
    # startupProbe: false
