apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: '^4.5.2'
  interval: 5m
  values:
    controller:
      service:
        externalTrafficPolicy: 'Local'
        annotations:
          service.beta.kubernetes.io/ovh-loadbalancer-proxy-protocol: 'v2'
      config:
        use-proxy-protocol: true
        real-ip-header: 'proxy_protocol'
        proxy-real-ip-cidr: '10.124.130.47/32,10.124.128.143/32,10.124.131.226/32,10.124.130.55/32' # cloud provider and load-balancer specific, update when re-deploying/switching the load balancer
