apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - european-transport-feeds-website
  - european-transport-feeds-data
  - public-transport-data-scraper-legacy-proxy
  - vbb-departure-hotline
  - db-rest
  - bahn-guru
  - example-app
  - chore-score-bot
  - lod-codefor-de-api
  - lod-codefor-de-frontend
